name: Deploy to GitHub Pages


on:
    push:
        branches:
            - main


jobs:
    build-and-deploy:
        runs-on: ubuntu-latest


        steps:
            - name: Inject env variables
              run:    |
                    echo "REACT_APP_SUPABASE_URL=${{ secrets.REACT_APP_SUPABASE_URL }}" >> .env:
                    echo "REACT_APP_SUPABASE_KEY=${{ secrets.REACT_APP_SUPABASE_KEY }}" >> .env:
            
            